--- #YAML:1.0
name:               Lingua-EN-Nickname
version:            1.17
abstract:           Genealogical nickname matching (Liz=Beth)
author:
    - Brian Lalonde (brian@webcoder.info)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
